export const GET_ABOUT_US_REQUEST = "GET_ABOUT_US_REQUEST";
export const GET_ABOUT_US_SUCCESS = "GET_ABOUT_US_SUCCESS";
export const GET_ABOUT_US_ERROR = "GET_ABOUT_US_ERROR"


export const CREATE_ABOUT_US_REQUEST = "CREATE_ABOUT_US_REQUEST";
export const CREATE_ABOUT_US_SUCCESS = "CREATE_ABOUT_US_SUCCESS";
export const CREATE_ABOUT_US_ERROR = "CREATE_ABOUT_US_ERROR";


export const EDIT_ABOUT_US_REQUEST = "EDIT_ABOUT_US_REQUEST";
export const EDIT_ABOUT_US_SUCCESS = "EDIT_ABOUT_US_SUCCESS";
export const EDIT_ABOUT_US_ERROR = "EDIT_ABOUT_US_ERROR"


export const ACTIVE_ABOUT_US_REQUEST = "ACTIVE_ABOUT_US_REQUEST";
export const ACTIVE_ABOUT_US_SUCCESS = "ACTIVE_ABOUT_US_SUCCESS";
export const ACTIVE_ABOUT_US_ERROR = "ACTIVE_ABOUT_US_ERROR"

export const INACTIVE_ABOUT_US_REQUEST = "INACTIVE_ABOUT_US_REQUEST";
export const INACTIVE_ABOUT_US_SUCCESS = "INACTIVE_ABOUT_US_SUCCESS";
export const INACTIVE_ABOUT_US_ERROR = "INACTIVE_ABOUT_US_ERROR";


export const DELETE_ABOUT_US_REQUEST = "DELETE_ABOUT_US_REQUEST";
export const DELETE_ABOUT_US_SUCCESS = "DELETE_ABOUT_US_SUCCESS";
export const DELETE_ABOUT_US_ERROR = "DELETE_ABOUT_US_ERROR"


export const UPLOAD_ABOUT_US_IMAGES_REQUEST = "UPLOAD_ABOUT_US_IMAGES_REQUEST";
export const UPLOAD_ABOUT_US_IMAGES_SUCCESS = "UPLOAD_ABOUT_US_IMAGES_SUCCESS";
export const UPLOAD_ABOUT_US_IMAGES_FAILURE = "UPLOAD_ABOUT_US_IMAGES_FAILURE"


export const FETCH_ABOUT_US_IMAGES_REQUEST = "FETCH_ABOUT_US_IMAGES_REQUEST";
export const FETCH_ABOUT_US_IMAGES_SUCCESS = "FETCH_ABOUT_US_IMAGES_SUCCESS";
export const FETCH_ABOUT_US_IMAGES_ERROR = "FETCH_ABOUT_US_IMAGES_ERROR";



export const DELETE_ABOUT_US_IMAGE_REQUEST = "DELETE_ABOUT_US_IMAGE_REQUEST";
export const DELETE_ABOUT_US_IMAGE_SUCCESS = "DELETE_ABOUT_US_IMAGE_SUCCESS";
export const DELETE_ABOUT_US_IMAGE_FAILURE = "DELETE_ABOUT_US_IMAGE_FAILURE";


export const INACTIVE_ABOUT_US_IMAGE_REQUEST = "INACTIVE_ABOUT_US_IMAGE_REQUEST";
export const INACTIVE_ABOUT_US_IMAGE_SUCCESS = "INACTIVE_ABOUT_US_IMAGE_SUCCESS";
export const INACTIVE_ABOUT_US_IMAGE_ERROR = "INACTIVE_ABOUT_US_IMAGE_ERROR";

export const ACTIVE_ABOUT_US_IMAGE_REQUEST = "ACTIVE_ABOUT_US_IMAGE_REQUEST";
export const ACTIVE_ABOUT_US_IMAGE_SUCCESS = "ACTIVE_ABOUT_US_IMAGE_SUCCESS";
export const ACTIVE_ABOUT_US_IMAGE_ERROR = "ACTIVE_ABOUT_US_IMAGE_ERROR";


