export const GET_CAUSES_STATS_REQUEST = "GET_CAUSES_STATS_REQUEST";
export const GET_CAUSES_STATS_SUCCESS = "GET_CAUSES_STATS_SUCCESS";
export const GET_CAUSES_STATS_ERROR = "GET_CAUSES_STATS_ERROR"


export const CREATE_CAUSES_STATS_REQUEST = "CREATE_CAUSES_STATS_REQUEST";
export const CREATE_CAUSES_STATS_SUCCESS = "CREATE_CAUSES_STATS_SUCCESS";
export const CREATE_CAUSES_STATS_ERROR = "CREATE_CAUSES_STATS_ERROR";


export const EDIT_CAUSES_STATS_REQUEST = "EDIT_CAUSES_STATS_REQUEST";
export const EDIT_CAUSES_STATS_SUCCESS = "EDIT_CAUSES_STATS_SUCCESS";
export const EDIT_CAUSES_STATS_ERROR = "EDIT_CAUSES_STATS_ERROR"


export const ACTIVE_CAUSES_STATS_REQUEST = "ACTIVE_CAUSES_STATS_REQUEST";
export const ACTIVE_CAUSES_STATS_SUCCESS = "ACTIVE_CAUSES_STATS_SUCCESS";
export const ACTIVE_CAUSES_STATS_ERROR = "ACTIVE_CAUSES_STATS_ERROR"

export const INACTIVE_CAUSES_STATS_REQUEST = "INACTIVE_CAUSES_STATS_REQUEST";
export const INACTIVE_CAUSES_STATS_SUCCESS = "INACTIVE_CAUSES_STATS_SUCCESS";
export const INACTIVE_CAUSES_STATS_ERROR = "INACTIVE_CAUSES_STATS_ERROR";


export const DELETE_CAUSES_STATS_REQUEST = "DELETE_CAUSES_STATS_REQUEST";
export const DELETE_CAUSES_STATS_SUCCESS = "DELETE_CAUSES_STATS_SUCCESS";
export const DELETE_CAUSES_STATS_ERROR = "DELETE_CAUSES_STATS_ERROR"


export const UPLOAD_CAUSES_STATS_IMAGES_REQUEST = "UPLOAD_CAUSES_STATS_IMAGES_REQUEST";
export const UPLOAD_CAUSES_STATS_IMAGES_SUCCESS = "UPLOAD_CAUSES_STATS_IMAGES_SUCCESS";
export const UPLOAD_CAUSES_STATS_IMAGES_FAILURE = "UPLOAD_CAUSES_STATS_IMAGES_FAILURE"


export const FETCH_CAUSES_STATS_IMAGES_REQUEST = "FETCH_CAUSES_STATS_IMAGES_REQUEST";
export const FETCH_CAUSES_STATS_IMAGES_SUCCESS = "FETCH_CAUSES_STATS_IMAGES_SUCCESS";
export const FETCH_CAUSES_STATS_IMAGES_ERROR = "FETCH_CAUSES_STATS_IMAGES_ERROR";



export const DELETE_CAUSES_STATS_IMAGE_REQUEST = "DELETE_CAUSES_STATS_IMAGE_REQUEST";
export const DELETE_CAUSES_STATS_IMAGE_SUCCESS = "DELETE_CAUSES_STATS_IMAGE_SUCCESS";
export const DELETE_CAUSES_STATS_IMAGE_FAILURE = "DELETE_CAUSES_STATS_IMAGE_FAILURE";


export const INACTIVE_CAUSES_STATS_IMAGE_REQUEST = "INACTIVE_CAUSES_STATS_IMAGE_REQUEST";
export const INACTIVE_CAUSES_STATS_IMAGE_SUCCESS = "INACTIVE_CAUSES_STATS_IMAGE_SUCCESS";
export const INACTIVE_CAUSES_STATS_IMAGE_ERROR = "INACTIVE_CAUSES_STATS_IMAGE_ERROR";

export const ACTIVE_CAUSES_STATS_IMAGE_REQUEST = "ACTIVE_CAUSES_STATS_IMAGE_REQUEST";
export const ACTIVE_CAUSES_STATS_IMAGE_SUCCESS = "ACTIVE_CAUSES_STATS_IMAGE_SUCCESS";
export const ACTIVE_CAUSES_STATS_IMAGE_ERROR = "ACTIVE_CAUSES_STATS_IMAGE_ERROR";


