export const GET_COMPANY_DETAILS_REQUEST = "GET_COMPANY_DETAILS_REQUEST";
export const GET_COMPANY_DETAILS_SUCCESS = "GET_COMPANY_DETAILS_SUCCESS";
export const GET_COMPANY_DETAILS_ERROR = "GET_COMPANY_DETAILS_ERROR"

export const CREATE_COMPANY_DETAILS_REQUEST = "CREATE_COMPANY_DETAILS_REQUEST";
export const CREATE_COMPANY_DETAILS_SUCCESS = "CREATE_COMPANY_DETAILS_SUCCESS";
export const CREATE_COMPANY_DETAILS_ERROR = "CREATE_COMPANY_DETAILS_ERROR"