export const GET_FEATURED_CAUSE_REQUEST = "GET_FEATURED_CAUSE_REQUEST";
export const GET_FEATURED_CAUSE_SUCCESS = "GET_FEATURED_CAUSE_SUCCESS";
export const GET_FEATURED_CAUSE_ERROR = "GET_FEATURED_CAUSE_ERROR"


export const CREATE_FEATURED_CAUSE_REQUEST = "CREATE_FEATURED_CAUSE_REQUEST";
export const CREATE_FEATURED_CAUSE_SUCCESS = "CREATE_FEATURED_CAUSE_SUCCESS";
export const CREATE_FEATURED_CAUSE_ERROR = "CREATE_FEATURED_CAUSE_ERROR";


export const EDIT_FEATURED_CAUSE_REQUEST = "EDIT_FEATURED_CAUSE_REQUEST";
export const EDIT_FEATURED_CAUSE_SUCCESS = "EDIT_FEATURED_CAUSE_SUCCESS";
export const EDIT_FEATURED_CAUSE_ERROR = "EDIT_FEATURED_CAUSE_ERROR"


export const ACTIVE_FEATURED_CAUSE_REQUEST = "ACTIVE_FEATURED_CAUSE_REQUEST";
export const ACTIVE_FEATURED_CAUSE_SUCCESS = "ACTIVE_FEATURED_CAUSE_SUCCESS";
export const ACTIVE_FEATURED_CAUSE_ERROR = "ACTIVE_FEATURED_CAUSE_ERROR"

export const INACTIVE_FEATURED_CAUSE_REQUEST = "INACTIVE_FEATURED_CAUSE_REQUEST";
export const INACTIVE_FEATURED_CAUSE_SUCCESS = "INACTIVE_FEATURED_CAUSE_SUCCESS";
export const INACTIVE_FEATURED_CAUSE_ERROR = "INACTIVE_FEATURED_CAUSE_ERROR";


export const DELETE_FEATURED_CAUSE_REQUEST = "DELETE_FEATURED_CAUSE_REQUEST";
export const DELETE_FEATURED_CAUSE_SUCCESS = "DELETE_FEATURED_CAUSE_SUCCESS";
export const DELETE_FEATURED_CAUSE_ERROR = "DELETE_FEATURED_CAUSE_ERROR"


export const UPLOAD_FEATURED_CAUSE_IMAGES_REQUEST = "UPLOAD_FEATURED_CAUSE_IMAGES_REQUEST";
export const UPLOAD_FEATURED_CAUSE_IMAGES_SUCCESS = "UPLOAD_FEATURED_CAUSE_IMAGES_SUCCESS";
export const UPLOAD_FEATURED_CAUSE_IMAGES_FAILURE = "UPLOAD_FEATURED_CAUSE_IMAGES_FAILURE"


export const FETCH_FEATURED_CAUSE_IMAGES_REQUEST = "FETCH_FEATURED_CAUSE_IMAGES_REQUEST";
export const FETCH_FEATURED_CAUSE_IMAGES_SUCCESS = "FETCH_FEATURED_CAUSE_IMAGES_SUCCESS";
export const FETCH_FEATURED_CAUSE_IMAGES_ERROR = "FETCH_FEATURED_CAUSE_IMAGES_ERROR";



export const DELETE_FEATURED_CAUSE_IMAGE_REQUEST = "DELETE_FEATURED_CAUSE_IMAGE_REQUEST";
export const DELETE_FEATURED_CAUSE_IMAGE_SUCCESS = "DELETE_FEATURED_CAUSE_IMAGE_SUCCESS";
export const DELETE_FEATURED_CAUSE_IMAGE_FAILURE = "DELETE_FEATURED_CAUSE_IMAGE_FAILURE";


export const INACTIVE_FEATURED_CAUSE_IMAGE_REQUEST = "INACTIVE_FEATURED_CAUSE_IMAGE_REQUEST";
export const INACTIVE_FEATURED_CAUSE_IMAGE_SUCCESS = "INACTIVE_FEATURED_CAUSE_IMAGE_SUCCESS";
export const INACTIVE_FEATURED_CAUSE_IMAGE_ERROR = "INACTIVE_FEATURED_CAUSE_IMAGE_ERROR";

export const ACTIVE_FEATURED_CAUSE_IMAGE_REQUEST = "ACTIVE_FEATURED_CAUSE_IMAGE_REQUEST";
export const ACTIVE_FEATURED_CAUSE_IMAGE_SUCCESS = "ACTIVE_FEATURED_CAUSE_IMAGE_SUCCESS";
export const ACTIVE_FEATURED_CAUSE_IMAGE_ERROR = "ACTIVE_FEATURED_CAUSE_IMAGE_ERROR";