
export const UPLOAD_FOOTER_BG_IMAGES_REQUEST = "UPLOAD_FOOTER_BG_IMAGES_REQUEST";
export const UPLOAD_FOOTER_BG_IMAGES_SUCCESS = "UPLOAD_FOOTER_BG_IMAGES_SUCCESS";
export const UPLOAD_FOOTER_BG_IMAGES_FAILURE = "UPLOAD_FOOTER_BG_IMAGES_FAILURE"

export const FETCH_FOOTER_BG_IMAGES_REQUEST = "FETCH_FOOTER_BG_IMAGES_REQUEST";
export const FETCH_FOOTER_BG_IMAGES_SUCCESS = "FETCH_FOOTER_BG_IMAGES_SUCCESS";
export const FETCH_FOOTER_BG_IMAGES_ERROR = "FETCH_FOOTER_BG_IMAGES_ERROR";



export const DELETE_FOOTER_BG_IMAGE_REQUEST = "DELETE_FOOTER_BG_IMAGE_REQUEST";
export const DELETE_FOOTER_BG_IMAGE_SUCCESS = "DELETE_FOOTER_BG_IMAGE_SUCCESS";
export const DELETE_FOOTER_BG_IMAGE_FAILURE = "DELETE_FOOTER_BG_IMAGE_FAILURE";


export const INACTIVE_FOOTER_BG_IMAGE_REQUEST = "INACTIVE_FOOTER_BG_IMAGE_REQUEST";
export const INACTIVE_FOOTER_BG_IMAGE_SUCCESS = "INACTIVE_FOOTER_BG_IMAGE_SUCCESS";
export const INACTIVE_FOOTER_BG_IMAGE_ERROR = "INACTIVE_FOOTER_BG_IMAGE_ERROR";

export const ACTIVE_FOOTER_BG_IMAGE_REQUEST = "ACTIVE_FOOTER_BG_IMAGE_REQUEST";
export const ACTIVE_FOOTER_BG_IMAGE_SUCCESS = "ACTIVE_FOOTER_BG_IMAGE_SUCCESS";
export const ACTIVE_FOOTER_BG_IMAGE_ERROR = "ACTIVE_FOOTER_BG_IMAGE_ERROR";