export const GET_HERO_FEATURED_CAUSE_REQUEST = "GET_HERO_FEATURED_CAUSE_REQUEST";
export const GET_HERO_FEATURED_CAUSE_SUCCESS = "GET_HERO_FEATURED_CAUSE_SUCCESS";
export const GET_HERO_FEATURED_CAUSE_ERROR = "GET_HERO_FEATURED_CAUSE_ERROR"


export const CREATE_HERO_FEATURED_CAUSE_REQUEST = "CREATE_HERO_FEATURED_CAUSE_REQUEST";
export const CREATE_HERO_FEATURED_CAUSE_SUCCESS = "CREATE_HERO_FEATURED_CAUSE_SUCCESS";
export const CREATE_HERO_FEATURED_CAUSE_ERROR = "CREATE_HERO_FEATURED_CAUSE_ERROR";


export const EDIT_HERO_FEATURED_CAUSE_REQUEST = "EDIT_HERO_FEATURED_CAUSE_REQUEST";
export const EDIT_HERO_FEATURED_CAUSE_SUCCESS = "EDIT_HERO_FEATURED_CAUSE_SUCCESS";
export const EDIT_HERO_FEATURED_CAUSE_ERROR = "EDIT_HERO_FEATURED_CAUSE_ERROR"


export const ACTIVE_HERO_FEATURED_CAUSE_REQUEST = "ACTIVE_HERO_FEATURED_CAUSE_REQUEST";
export const ACTIVE_HERO_FEATURED_CAUSE_SUCCESS = "ACTIVE_HERO_FEATURED_CAUSE_SUCCESS";
export const ACTIVE_HERO_FEATURED_CAUSE_ERROR = "ACTIVE_HERO_FEATURED_CAUSE_ERROR"

export const INACTIVE_HERO_FEATURED_CAUSE_REQUEST = "INACTIVE_HERO_FEATURED_CAUSE_REQUEST";
export const INACTIVE_HERO_FEATURED_CAUSE_SUCCESS = "INACTIVE_HERO_FEATURED_CAUSE_SUCCESS";
export const INACTIVE_HERO_FEATURED_CAUSE_ERROR = "INACTIVE_HERO_FEATURED_CAUSE_ERROR";


export const DELETE_HERO_FEATURED_CAUSE_REQUEST = "DELETE_HERO_FEATURED_CAUSE_REQUEST";
export const DELETE_HERO_FEATURED_CAUSE_SUCCESS = "DELETE_HERO_FEATURED_CAUSE_SUCCESS";
export const DELETE_HERO_FEATURED_CAUSE_ERROR = "DELETE_HERO_FEATURED_CAUSE_ERROR"


export const UPLOAD_HERO_FEATURED_CAUSE_IMAGES_REQUEST = "UPLOAD_HERO_FEATURED_CAUSE_IMAGES_REQUEST";
export const UPLOAD_HERO_FEATURED_CAUSE_IMAGES_SUCCESS = "UPLOAD_HERO_FEATURED_CAUSE_IMAGES_SUCCESS";
export const UPLOAD_HERO_FEATURED_CAUSE_IMAGES_FAILURE = "UPLOAD_HERO_FEATURED_CAUSE_IMAGES_FAILURE"


export const FETCH_HERO_FEATURED_CAUSE_IMAGES_REQUEST = "FETCH_HERO_FEATURED_CAUSE_IMAGES_REQUEST";
export const FETCH_HERO_FEATURED_CAUSE_IMAGES_SUCCESS = "FETCH_HERO_FEATURED_CAUSE_IMAGES_SUCCESS";
export const FETCH_HERO_FEATURED_CAUSE_IMAGES_ERROR = "FETCH_HERO_FEATURED_CAUSE_IMAGES_ERROR";



export const DELETE_HERO_FEATURED_CAUSE_IMAGE_REQUEST = "DELETE_HERO_FEATURED_CAUSE_IMAGE_REQUEST";
export const DELETE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS = "DELETE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS";
export const DELETE_HERO_FEATURED_CAUSE_IMAGE_FAILURE = "DELETE_HERO_FEATURED_CAUSE_IMAGE_FAILURE";


export const INACTIVE_HERO_FEATURED_CAUSE_IMAGE_REQUEST = "INACTIVE_HERO_FEATURED_CAUSE_IMAGE_REQUEST";
export const INACTIVE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS = "INACTIVE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS";
export const INACTIVE_HERO_FEATURED_CAUSE_IMAGE_ERROR = "INACTIVE_HERO_FEATURED_CAUSE_IMAGE_ERROR";

export const ACTIVE_HERO_FEATURED_CAUSE_IMAGE_REQUEST = "ACTIVE_HERO_FEATURED_CAUSE_IMAGE_REQUEST";
export const ACTIVE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS = "ACTIVE_HERO_FEATURED_CAUSE_IMAGE_SUCCESS";
export const ACTIVE_HERO_FEATURED_CAUSE_IMAGE_ERROR = "ACTIVE_HERO_FEATURED_CAUSE_IMAGE_ERROR";