export const GET_HERO_REQUEST = "GET_HERO_REQUEST";
export const GET_HERO_SUCCESS = "GET_HERO_SUCCESS";
export const GET_HERO_ERROR = "GET_HERO_ERROR"


export const CREATE_HERO_REQUEST = "CREATE_HERO_REQUEST";
export const CREATE_HERO_SUCCESS = "CREATE_HERO_SUCCESS";
export const CREATE_HERO_ERROR = "CREATE_HERO_ERROR";


export const EDIT_HERO_REQUEST = "EDIT_HERO_REQUEST";
export const EDIT_HERO_SUCCESS = "EDIT_HERO_SUCCESS";
export const EDIT_HERO_ERROR = "EDIT_HERO_ERROR"


export const ACTIVE_HERO_REQUEST = "ACTIVE_HERO_REQUEST";
export const ACTIVE_HERO_SUCCESS = "ACTIVE_HERO_SUCCESS";
export const ACTIVE_HERO_ERROR = "ACTIVE_HERO_ERROR"

export const INACTIVE_HERO_REQUEST = "INACTIVE_HERO_REQUEST";
export const INACTIVE_HERO_SUCCESS = "INACTIVE_HERO_SUCCESS";
export const INACTIVE_HERO_ERROR = "INACTIVE_HERO_ERROR";


export const DELETE_HERO_REQUEST = "DELETE_HERO_REQUEST";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";
export const DELETE_HERO_ERROR = "DELETE_HERO_ERROR"


export const UPLOAD_HERO_IMAGES_REQUEST = "UPLOAD_HERO_IMAGES_REQUEST";
export const UPLOAD_HERO_IMAGES_SUCCESS = "UPLOAD_HERO_IMAGES_SUCCESS";
export const UPLOAD_HERO_IMAGES_FAILURE = "UPLOAD_HERO_IMAGES_FAILURE"


export const FETCH_HERO_IMAGES_REQUEST = "FETCH_HERO_IMAGES_REQUEST";
export const FETCH_HERO_IMAGES_SUCCESS = "FETCH_HERO_IMAGES_SUCCESS";
export const FETCH_HERO_IMAGES_ERROR = "FETCH_HERO_IMAGES_ERROR";



export const DELETE_HERO_IMAGE_REQUEST = "DELETE_HERO_IMAGE_REQUEST";
export const DELETE_HERO_IMAGE_SUCCESS = "DELETE_HERO_IMAGE_SUCCESS";
export const DELETE_HERO_IMAGE_FAILURE = "DELETE_HERO_IMAGE_FAILURE";


export const INACTIVE_HERO_IMAGE_REQUEST = "INACTIVE_HERO_IMAGE_REQUEST";
export const INACTIVE_HERO_IMAGE_SUCCESS = "INACTIVE_HERO_IMAGE_SUCCESS";
export const INACTIVE_HERO_IMAGE_ERROR = "INACTIVE_HERO_IMAGE_ERROR";

export const ACTIVE_HERO_IMAGE_REQUEST = "ACTIVE_HERO_IMAGE_REQUEST";
export const ACTIVE_HERO_IMAGE_SUCCESS = "ACTIVE_HERO_IMAGE_SUCCESS";
export const ACTIVE_HERO_IMAGE_ERROR = "ACTIVE_HERO_IMAGE_ERROR";