export const GET_HERO_CARD_REQUEST = "GET_HERO_CARD_REQUEST";
export const GET_HERO_CARD_SUCCESS = "GET_HERO_CARD_SUCCESS";
export const GET_HERO_CARD_ERROR = "GET_HERO_CARD_ERROR"


export const CREATE_HERO_CARD_REQUEST = "CREATE_HERO_CARD_REQUEST";
export const CREATE_HERO_CARD_SUCCESS = "CREATE_HERO_CARD_SUCCESS";
export const CREATE_HERO_CARD_ERROR = "CREATE_HERO_CARD_ERROR";


export const EDIT_HERO_CARD_REQUEST = "EDIT_HERO_CARD_REQUEST";
export const EDIT_HERO_CARD_SUCCESS = "EDIT_HERO_CARD_SUCCESS";
export const EDIT_HERO_CARD_ERROR = "EDIT_HERO_CARD_ERROR"


export const ACTIVE_HERO_CARD_REQUEST = "ACTIVE_HERO_CARD_REQUEST";
export const ACTIVE_HERO_CARD_SUCCESS = "ACTIVE_HERO_CARD_SUCCESS";
export const ACTIVE_HERO_CARD_ERROR = "ACTIVE_HERO_CARD_ERROR"

export const INACTIVE_HERO_CARD_REQUEST = "INACTIVE_HERO_CARD_REQUEST";
export const INACTIVE_HERO_CARD_SUCCESS = "INACTIVE_HERO_CARD_SUCCESS";
export const INACTIVE_HERO_CARD_ERROR = "INACTIVE_HERO_CARD_ERROR";


export const DELETE_HERO_CARD_REQUEST = "DELETE_HERO_CARD_REQUEST";
export const DELETE_HERO_CARD_SUCCESS = "DELETE_HERO_CARD_SUCCESS";
export const DELETE_HERO_CARD_ERROR = "DELETE_HERO_CARD_ERROR"


export const UPLOAD_HERO_CARD_IMAGES_REQUEST = "UPLOAD_HERO_CARD_IMAGES_REQUEST";
export const UPLOAD_HERO_CARD_IMAGES_SUCCESS = "UPLOAD_HERO_CARD_IMAGES_SUCCESS";
export const UPLOAD_HERO_CARD_IMAGES_FAILURE = "UPLOAD_HERO_CARD_IMAGES_FAILURE"


export const FETCH_HERO_CARD_IMAGES_REQUEST = "FETCH_HERO_CARD_IMAGES_REQUEST";
export const FETCH_HERO_CARD_IMAGES_SUCCESS = "FETCH_HERO_CARD_IMAGES_SUCCESS";
export const FETCH_HERO_CARD_IMAGES_ERROR = "FETCH_HERO_CARD_IMAGES_ERROR";



export const DELETE_HERO_CARD_IMAGE_REQUEST = "DELETE_HERO_CARD_IMAGE_REQUEST";
export const DELETE_HERO_CARD_IMAGE_SUCCESS = "DELETE_HERO_CARD_IMAGE_SUCCESS";
export const DELETE_HERO_CARD_IMAGE_FAILURE = "DELETE_HERO_CARD_IMAGE_FAILURE";


export const INACTIVE_HERO_CARD_IMAGE_REQUEST = "INACTIVE_HERO_CARD_IMAGE_REQUEST";
export const INACTIVE_HERO_CARD_IMAGE_SUCCESS = "INACTIVE_HERO_CARD_IMAGE_SUCCESS";
export const INACTIVE_HERO_CARD_IMAGE_ERROR = "INACTIVE_HERO_CARD_IMAGE_ERROR";

export const ACTIVE_HERO_CARD_IMAGE_REQUEST = "ACTIVE_HERO_CARD_IMAGE_REQUEST";
export const ACTIVE_HERO_CARD_IMAGE_SUCCESS = "ACTIVE_HERO_CARD_IMAGE_SUCCESS";
export const ACTIVE_HERO_CARD_IMAGE_ERROR = "ACTIVE_HERO_CARD_IMAGE_ERROR";


