export const GET_HERO_REQUEST = "GET_HERO_REQUES";
export const GET_HERO_SUCCESS = "GET_HERO_SUCCESS";
export const GET_HERO_ERROR = "GET_HERO_ERROR"

export const CREATE_HERO_REQUEST = "CREATE_HERO_REQUEST";
export const CREATE_HERO_SUCCESS = "CREATE_HERO_SUCCESS";
export const CREATE_HERO_ERROR = "CREATE_HERO_ERROR";


export const EDIT_HERO_REQUEST = "EDIT_HERO_REQUEST";
export const EDIT_HERO_SUCCESS = "EDIT_HERO_SUCCESS";
export const EDIT_HERO_ERROR = "EDIT_HERO_ERROR"


export const ACTIVE_HERO_REQUEST = "ACTIVE_HERO_REQUEST";
export const ACTIVE_HERO_SUCCESS = "ACTIVE_HERO_SUCCESS";
export const ACTIVE_HERO_ERROR = "ACTIVE_HERO_ERROR"

export const INACTIVE_HERO_REQUEST = "INACTIVE_HERO_REQUEST";
export const INACTIVE_HERO_SUCCESS = "INACTIVE_HERO_SUCCESS";
export const INACTIVE_HERO_ERROR = "INACTIVE_HERO_ERROR";


export const DELETE_HERO_REQUEST = "DELETE_HERO_REQUEST";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";
export const DELETE_HERO_ERROR = "DELETE_HERO_ERROR"