export const GET_OUR_CAUSES_REQUEST = "GET_OUR_CAUSES_REQUEST";
export const GET_OUR_CAUSES_SUCCESS = "GET_OUR_CAUSES_SUCCESS";
export const GET_OUR_CAUSES_ERROR = "GET_OUR_CAUSES_ERROR"


export const CREATE_OUR_CAUSES_REQUEST = "CREATE_OUR_CAUSES_REQUEST";
export const CREATE_OUR_CAUSES_SUCCESS = "CREATE_OUR_CAUSES_SUCCESS";
export const CREATE_OUR_CAUSES_ERROR = "CREATE_OUR_CAUSES_ERROR";


export const EDIT_OUR_CAUSES_REQUEST = "EDIT_OUR_CAUSES_REQUEST";
export const EDIT_OUR_CAUSES_SUCCESS = "EDIT_OUR_CAUSES_SUCCESS";
export const EDIT_OUR_CAUSES_ERROR = "EDIT_OUR_CAUSES_ERROR"


export const ACTIVE_OUR_CAUSES_REQUEST = "ACTIVE_OUR_CAUSES_REQUEST";
export const ACTIVE_OUR_CAUSES_SUCCESS = "ACTIVE_OUR_CAUSES_SUCCESS";
export const ACTIVE_OUR_CAUSES_ERROR = "ACTIVE_OUR_CAUSES_ERROR"

export const INACTIVE_OUR_CAUSES_REQUEST = "INACTIVE_OUR_CAUSES_REQUEST";
export const INACTIVE_OUR_CAUSES_SUCCESS = "INACTIVE_OUR_CAUSES_SUCCESS";
export const INACTIVE_OUR_CAUSES_ERROR = "INACTIVE_OUR_CAUSES_ERROR";


export const DELETE_OUR_CAUSES_REQUEST = "DELETE_OUR_CAUSES_REQUEST";
export const DELETE_OUR_CAUSES_SUCCESS = "DELETE_OUR_CAUSES_SUCCESS";
export const DELETE_OUR_CAUSES_ERROR = "DELETE_OUR_CAUSES_ERROR"


export const UPLOAD_OUR_CAUSES_IMAGES_REQUEST = "UPLOAD_OUR_CAUSES_IMAGES_REQUEST";
export const UPLOAD_OUR_CAUSES_IMAGES_SUCCESS = "UPLOAD_OUR_CAUSES_IMAGES_SUCCESS";
export const UPLOAD_OUR_CAUSES_IMAGES_FAILURE = "UPLOAD_OUR_CAUSES_IMAGES_FAILURE"


export const FETCH_OUR_CAUSES_IMAGES_REQUEST = "FETCH_OUR_CAUSES_IMAGES_REQUEST";
export const FETCH_OUR_CAUSES_IMAGES_SUCCESS = "FETCH_OUR_CAUSES_IMAGES_SUCCESS";
export const FETCH_OUR_CAUSES_IMAGES_ERROR = "FETCH_OUR_CAUSES_IMAGES_ERROR";



export const DELETE_OUR_CAUSES_IMAGE_REQUEST = "DELETE_OUR_CAUSES_IMAGE_REQUEST";
export const DELETE_OUR_CAUSES_IMAGE_SUCCESS = "DELETE_OUR_CAUSES_IMAGE_SUCCESS";
export const DELETE_OUR_CAUSES_IMAGE_FAILURE = "DELETE_OUR_CAUSES_IMAGE_FAILURE";


export const INACTIVE_OUR_CAUSES_IMAGE_REQUEST = "INACTIVE_OUR_CAUSES_IMAGE_REQUEST";
export const INACTIVE_OUR_CAUSES_IMAGE_SUCCESS = "INACTIVE_OUR_CAUSES_IMAGE_SUCCESS";
export const INACTIVE_OUR_CAUSES_IMAGE_ERROR = "INACTIVE_OUR_CAUSES_IMAGE_ERROR";

export const ACTIVE_OUR_CAUSES_IMAGE_REQUEST = "ACTIVE_OUR_CAUSES_IMAGE_REQUEST";
export const ACTIVE_OUR_CAUSES_IMAGE_SUCCESS = "ACTIVE_OUR_CAUSES_IMAGE_SUCCESS";
export const ACTIVE_OUR_CAUSES_IMAGE_ERROR = "ACTIVE_OUR_CAUSES_IMAGE_ERROR";


