
export const ON_SELECT_APP_TAB = 'ON_SELECT_APP_TAB';
export const DRAWER_OPEN = 'DRAWER_OPEN';
export const ON_CONFI_DIALOG_OPEN = 'ON_CONFI_DIALOG_OPEN';
export const ON_POPOVER_DIALOG_OPEN = 'ON_POPOVER_DIALOG_OPEN';





