export const GET_UP_COMING_EVENTS_REQUEST = "GET_UP_COMING_EVENTS_REQUEST";
export const GET_UP_COMING_EVENTS_SUCCESS = "GET_UP_COMING_EVENTS_SUCCESS";
export const GET_UP_COMING_EVENTS_ERROR = "GET_UP_COMING_EVENTS_ERROR"


export const CREATE_UP_COMING_EVENTS_REQUEST = "CREATE_UP_COMING_EVENTS_REQUEST";
export const CREATE_UP_COMING_EVENTS_SUCCESS = "CREATE_UP_COMING_EVENTS_SUCCESS";
export const CREATE_UP_COMING_EVENTS_ERROR = "CREATE_UP_COMING_EVENTS_ERROR";


export const EDIT_UP_COMING_EVENTS_REQUEST = "EDIT_UP_COMING_EVENTS_REQUEST";
export const EDIT_UP_COMING_EVENTS_SUCCESS = "EDIT_UP_COMING_EVENTS_SUCCESS";
export const EDIT_UP_COMING_EVENTS_ERROR = "EDIT_UP_COMING_EVENTS_ERROR"


export const ACTIVE_UP_COMING_EVENTS_REQUEST = "ACTIVE_UP_COMING_EVENTS_REQUEST";
export const ACTIVE_UP_COMING_EVENTS_SUCCESS = "ACTIVE_UP_COMING_EVENTS_SUCCESS";
export const ACTIVE_UP_COMING_EVENTS_ERROR = "ACTIVE_UP_COMING_EVENTS_ERROR"

export const INACTIVE_UP_COMING_EVENTS_REQUEST = "INACTIVE_UP_COMING_EVENTS_REQUEST";
export const INACTIVE_UP_COMING_EVENTS_SUCCESS = "INACTIVE_UP_COMING_EVENTS_SUCCESS";
export const INACTIVE_UP_COMING_EVENTS_ERROR = "INACTIVE_UP_COMING_EVENTS_ERROR";


export const DELETE_UP_COMING_EVENTS_REQUEST = "DELETE_UP_COMING_EVENTS_REQUEST";
export const DELETE_UP_COMING_EVENTS_SUCCESS = "DELETE_UP_COMING_EVENTS_SUCCESS";
export const DELETE_UP_COMING_EVENTS_ERROR = "DELETE_UP_COMING_EVENTS_ERROR"


export const UPLOAD_UP_COMING_EVENTS_IMAGES_REQUEST = "UPLOAD_UP_COMING_EVENTS_IMAGES_REQUEST";
export const UPLOAD_UP_COMING_EVENTS_IMAGES_SUCCESS = "UPLOAD_UP_COMING_EVENTS_IMAGES_SUCCESS";
export const UPLOAD_UP_COMING_EVENTS_IMAGES_FAILURE = "UPLOAD_UP_COMING_EVENTS_IMAGES_FAILURE"


export const FETCH_UP_COMING_EVENTS_IMAGES_REQUEST = "FETCH_UP_COMING_EVENTS_IMAGES_REQUEST";
export const FETCH_UP_COMING_EVENTS_IMAGES_SUCCESS = "FETCH_UP_COMING_EVENTS_IMAGES_SUCCESS";
export const FETCH_UP_COMING_EVENTS_IMAGES_ERROR = "FETCH_UP_COMING_EVENTS_IMAGES_ERROR";



export const DELETE_UP_COMING_EVENTS_IMAGE_REQUEST = "DELETE_UP_COMING_EVENTS_IMAGE_REQUEST";
export const DELETE_UP_COMING_EVENTS_IMAGE_SUCCESS = "DELETE_UP_COMING_EVENTS_IMAGE_SUCCESS";
export const DELETE_UP_COMING_EVENTS_IMAGE_FAILURE = "DELETE_UP_COMING_EVENTS_IMAGE_FAILURE";


export const INACTIVE_UP_COMING_EVENTS_IMAGE_REQUEST = "INACTIVE_UP_COMING_EVENTS_IMAGE_REQUEST";
export const INACTIVE_UP_COMING_EVENTS_IMAGE_SUCCESS = "INACTIVE_UP_COMING_EVENTS_IMAGE_SUCCESS";
export const INACTIVE_UP_COMING_EVENTS_IMAGE_ERROR = "INACTIVE_UP_COMING_EVENTS_IMAGE_ERROR";

export const ACTIVE_UP_COMING_EVENTS_IMAGE_REQUEST = "ACTIVE_UP_COMING_EVENTS_IMAGE_REQUEST";
export const ACTIVE_UP_COMING_EVENTS_IMAGE_SUCCESS = "ACTIVE_UP_COMING_EVENTS_IMAGE_SUCCESS";
export const ACTIVE_UP_COMING_EVENTS_IMAGE_ERROR = "ACTIVE_UP_COMING_EVENTS_IMAGE_ERROR";